apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-amber-gpu-ws
  labels:
    k8s-app: deployment-amber-gpu-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: deployment-amber-gpu-ws
  template:
    metadata: 
      labels:
        k8s-app: deployment-amber-gpu-ws
    spec:
      containers:
      - name: mypod-gpu
        image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow
        resources:
           limits:
             memory: 64Gi
             cpu: 500m
             nvidia.com/gpu: 1
           requests:
             memory: 64Gi
             cpu: 500m
        command: ["sh", "-c", "sleep infinity"]
      nodeSelector:
        nautilus.io/disktype: nvme

